@startuml casos de uso
left to right direction
skinparam packageStyle rectangle

actor Doador
actor Instituição

package "FoodLink" {
  usecase "Cadastrar Usuário" as UC1
  usecase "Realizar Autenticação (Login)" as UC2
  usecase "Gerenciar Perfil e Endereço" as UC3
  usecase "Cadastrar Alimento" as UC4
  usecase "Atualizar Status (Entregue)" as UC5
  usecase "Cancelar Doação/Reserva" as UC6
  usecase "Visualizar Feed de Alimentos" as UC7
  usecase "Filtrar por Categoria" as UC8
  usecase "Reservar Alimento" as UC9
}

Doador -- UC1
Doador -- UC2
Doador -- UC3
Doador -- UC4
Doador -- UC5
Doador -- UC6

Instituição -- UC1
Instituição -- UC2
Instituição -- UC3
Instituição -- UC6
Instituição -- UC7
Instituição -- UC9

UC8 .> UC7 : <<extend>>
@enduml