@startuml sequencia
actor Instituição as Inst
boundary "Front-end\n(HTML/JS)" as Front
control "Back-end API\n(Python)" as API
database "Banco de Dados\n(SQL)" as BD

Inst -> Front: Clica em "Reservar" na Doação #1
Front -> API: POST /reserva (id_doacao, id_instituicao)
activate API
API -> BD: SELECT status FROM Doacao WHERE id = 1
activate BD
BD --> API: Retorna 'Disponível'
deactivate BD

API -> BD: UPDATE Doacao SET status='Reservado', inst_id=?
activate BD
BD --> API: Update Sucesso
deactivate BD

API --> Front: Retorna JSON (200 OK, Sucesso)
deactivate API
Front --> Inst: Exibe "Reserva confirmada! Endereço: X"
@enduml